"""Seed pages for official (non-NSP) sources.

Only domains that passed robots recon appear here; the fetcher re-checks each
one anyway, so an entry that later turns hostile is skipped, not forced.
"""

SEEDS = [
    # --- central government scheme owners ---
    ("AICTE", "https://www.aicte.gov.in/schemes/students-development-schemes",
     "All India Council for Technical Education", "central_govt"),
    ("UGC", "https://www.ugc.gov.in/Scholarship",
     "University Grants Commission", "central_govt"),
    ("MoTA", "https://tribal.nic.in/Scholarship.aspx",
     "Ministry of Tribal Affairs", "central_govt"),
    ("MoMA", "https://minorityaffairs.gov.in/",
     "Ministry of Minority Affairs", "central_govt"),
    ("MoSJE", "https://socialjustice.gov.in/schemes/33",
     "Ministry of Social Justice and Empowerment", "central_govt"),
    ("INSPIRE", "https://online-inspire.gov.in/",
     "Department of Science and Technology", "central_govt"),
    ("CSIR", "https://csirhrdg.res.in/",
     "CSIR Human Resource Development Group", "central_govt"),
    ("KSB", "https://ksb.gov.in/",
     "Kendriya Sainik Board", "central_govt"),
    ("DESW", "https://www.desw.gov.in/",
     "Department of Ex-Servicemen Welfare", "central_govt"),
    ("PMSSS", "https://www.aicte-jk-scholarship-gov.in/",
     "AICTE (PMSSS J&K and Ladakh)", "central_govt"),
    ("NTA", "https://www.nta.ac.in/", "National Testing Agency", "central_govt"),

    # --- state portals that were reachable ---
    ("Karnataka", "https://ssp.postmatric.karnataka.gov.in/",
     "Government of Karnataka", "state_govt"),
    ("Telangana", "https://telanganaepass.cgg.gov.in/",
     "Government of Telangana", "state_govt"),
    ("Kerala", "https://egrantz.kerala.gov.in/",
     "Government of Kerala", "state_govt"),
    ("Odisha", "https://scholarship.odisha.gov.in/",
     "Government of Odisha", "state_govt"),
    ("Rajasthan", "https://sje.rajasthan.gov.in/",
     "Government of Rajasthan", "state_govt"),
    ("Punjab", "https://scholarships.punjab.gov.in/",
     "Government of Punjab", "state_govt"),
    ("Haryana", "https://harchhatravratti.highereduhry.ac.in/",
     "Government of Haryana", "state_govt"),
    ("UP", "https://scholarship.up.gov.in/",
     "Government of Uttar Pradesh", "state_govt"),
    ("Chhattisgarh", "https://postmatric-scholarship.cg.nic.in/",
     "Government of Chhattisgarh", "state_govt"),
    ("HP", "https://hpepass.cgg.gov.in/",
     "Government of Himachal Pradesh", "state_govt"),
    ("Assam", "https://directorateofhighereducation.assam.gov.in/",
     "Government of Assam", "state_govt"),
    ("Uttarakhand", "https://uk.gov.in/", "Government of Uttarakhand", "state_govt"),
    ("Gujarat", "https://www.digitalgujarat.gov.in/",
     "Government of Gujarat", "state_govt"),
    ("Delhi", "https://edistrict.delhigovt.nic.in/",
     "Government of NCT of Delhi", "state_govt"),

    # --- foundations, PSUs, private ---
    ("TataTrusts", "https://www.tatatrusts.org/our-work/individual-grants-programme",
     "Tata Trusts", "ngo"),
    ("Reliance", "https://www.reliancefoundation.org/",
     "Reliance Foundation", "ngo"),
    ("SitaramJindal", "https://www.sitaramjindalfoundation.org/",
     "Sitaram Jindal Foundation", "ngo"),
    ("AdityaBirla", "https://www.adityabirlascholars.net/",
     "Aditya Birla Group", "private"),
    ("Santoor", "https://www.santoorscholarship.com/",
     "Wipro Consumer Care (Santoor)", "private"),
    ("FFE", "https://www.northsouth.org/",
     "Foundation for Excellence India Trust", "ngo"),
    ("ONGC", "https://ongcindia.com/", "Oil and Natural Gas Corporation", "psu"),
    ("NTPC", "https://www.ntpc.co.in/", "NTPC Limited", "psu"),
    ("SAIL", "https://sail.co.in/", "Steel Authority of India", "psu"),
    ("GAIL", "https://www.gailonline.com/", "GAIL India Limited", "psu"),
    ("Legrand", "https://www.legrand.co.in/", "Legrand India", "private"),
    ("Colgate", "https://www.colgate.co.in/", "Colgate-Palmolive India", "private"),
    ("LIC", "https://licindia.in/", "LIC Golden Jubilee Foundation", "private"),
]
